version: "3.8"

services:
  web:
    container_name: bike_price_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - FlASK_APP= app1.py
      - FLASK_RUN_HOST= 0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run --host=0.0.0.0 --port=5000
